"""initial

Revision ID: 11598a7d2153
Revises: 
Create Date: 2025-05-26 22:35:27.713404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11598a7d2153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_from_tracking', sa.Boolean(), nullable=False))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_from_tracking')

    # ### end Alembic commands ###
